# Generated by Django 2.2.5 on 2019-11-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20191113_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='qualification',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
