# Generated by Django 2.2.5 on 2019-11-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_regis',
            field=models.IntegerField(blank=True, null=True, verbose_name='maximum participant'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='qualification',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
