language: python

python: "3.7"

# don't clone more than necessary
git:
  depth: 1

install:
  - pip install -r requirements.txt

# script to run tests. Can also use make, e.g. "make test"
script: 
  - py manage.py makemigrations
  - py manage.py migrate
  - py manage.py test events/tests/