language: python

python: "3.6"

# don't clone more than necessary
git:
  depth: 1

install:
  - pip install -r requirements.txt

env: 
  - DEBUG = True
  - SECRET_KEY = '6a^izyf25(_w!%r+_9+gimq*w6&sc9cxrf5n@87b$d_+f^lca!'

# script to run tests. Can also use make, e.g. "make test"
script: 
  - python manage.py makemigrations
  - python manage.py
  - python manage.py test events/tests/