language: python

python: "3.6"

# don't clone more than necessary
git:
  depth: 1

install:
  - pip install -r requirements.txt

env: 
  - DEBUG = True

# script to run tests. Can also use make, e.g. "make test"
script: 
  - coverage run manage.py test events/tests

after_success:
  - codecov